export type ThemeColors = {
  page: string;
  card: string;
  header: string;
  headerBorder: string;
  cardBorder: string;
  border: string;
  borderStrong: string;
  text: string;
  textSecondary: string;
  textMuted: string;
  textInverse: string;
  primary: string;
  primarySoft: string;
  accentText: string;
  accentTextStrong: string;
  accentTextDeep: string;
  inputBg: string;
  headerTint: string;
  headerTintBorder: string;
  headerToggleBorder: string;
  danger: string;
  dangerBg: string;
  dangerBorder: string;
  errorText: string;
  savingsBg: string;
  savingsBorder: string;
  savingsText: string;
  extraText: string;
  tooltipBg: string;
  chartLine: string;
  chartTooltipLine: string;
  pieInset: string;
  modalBackdrop: string;
  calculatingBackdrop: string;
  snackbarBg: string;
  navButtonBg: string;
  saveBarBg: string;
  gridHeaderBg: string;
  gridOddRow: string;
  keyNumberBg: string;
  keyNumberText: string;
  keyOpBg: string;
  keyOpText: string;
  keyFnBg: string;
  keyFnText: string;
  keyEqualsBg: string;
  keyEqualsText: string;
  calcDisplayBg: string;
  switchTrackOff: string;
  switchTrackOn: string;
  switchThumb: string;
};

export const lightColors: ThemeColors = {
  page: "#f3f4f6",
  card: "#ffffff",
  header: "#ffffff",
  headerBorder: "#e5e7eb",
  cardBorder: "#dbeafe",
  border: "#e5e7eb",
  borderStrong: "#d1d5db",
  text: "#111827",
  textSecondary: "#374151",
  textMuted: "#6b7280",
  textInverse: "#ffffff",
  primary: "#2563eb",
  primarySoft: "#dbeafe",
  accentText: "#1e3a8a",
  accentTextStrong: "#1d4ed8",
  accentTextDeep: "#1e40af",
  inputBg: "#f9fafb",
  headerTint: "#eff6ff",
  headerTintBorder: "#dbeafe",
  headerToggleBorder: "#bfdbfe",
  danger: "#b91c1c",
  dangerBg: "#fef2f2",
  dangerBorder: "#fecaca",
  errorText: "#dc2626",
  savingsBg: "rgba(139, 228, 172, 0.5)",
  savingsBorder: "rgba(92, 228, 141, 0.5)",
  savingsText: "#14532d",
  extraText: "#047857",
  tooltipBg: "#f8fafc",
  chartLine: "#e5e7eb",
  chartTooltipLine: "rgba(17,24,39,0.28)",
  pieInset: "#ffffff",
  modalBackdrop: "rgba(17,24,39,0.45)",
  calculatingBackdrop: "rgba(17,24,39,0.28)",
  snackbarBg: "rgba(17,24,39,0.9)",
  navButtonBg: "#f9fafb",
  saveBarBg: "#f8fafc",
  gridHeaderBg: "#f3f4f6",
  gridOddRow: "#f9fafb",
  keyNumberBg: "#f3f4f6",
  keyNumberText: "#111827",
  keyOpBg: "#dbeafe",
  keyOpText: "#1d4ed8",
  keyFnBg: "#e5e7eb",
  keyFnText: "#374151",
  keyEqualsBg: "#2563eb",
  keyEqualsText: "#ffffff",
  calcDisplayBg: "#ffffff",
  switchTrackOff: "#d1d5db",
  switchTrackOn: "#93c5fd",
  switchThumb: "#ffffff",
};

export const darkColors: ThemeColors = {
  page: "#0f172a",
  card: "#1e293b",
  header: "#1e293b",
  headerBorder: "#334155",
  cardBorder: "#334155",
  border: "#334155",
  borderStrong: "#475569",
  text: "#f8fafc",
  textSecondary: "#cbd5e1",
  textMuted: "#94a3b8",
  textInverse: "#ffffff",
  primary: "#3b82f6",
  primarySoft: "#1e3a8a",
  accentText: "#93c5fd",
  accentTextStrong: "#60a5fa",
  accentTextDeep: "#93c5fd",
  inputBg: "#0f172a",
  headerTint: "#1e3a5f",
  headerTintBorder: "#1e40af",
  headerToggleBorder: "#3b82f6",
  danger: "#f87171",
  dangerBg: "#7f1d1d",
  dangerBorder: "#991b1b",
  errorText: "#f87171",
  savingsBg: "rgba(16, 185, 129, 0.18)",
  savingsBorder: "rgba(16, 185, 129, 0.35)",
  savingsText: "#86efac",
  extraText: "#34d399",
  tooltipBg: "#0f172a",
  chartLine: "#334155",
  chartTooltipLine: "rgba(248,250,252,0.35)",
  pieInset: "#1e293b",
  modalBackdrop: "rgba(2,6,23,0.62)",
  calculatingBackdrop: "rgba(2,6,23,0.5)",
  snackbarBg: "rgba(15,23,42,0.94)",
  navButtonBg: "#0f172a",
  saveBarBg: "#0f172a",
  gridHeaderBg: "#0f172a",
  gridOddRow: "#162032",
  keyNumberBg: "#334155",
  keyNumberText: "#f8fafc",
  keyOpBg: "#1e3a8a",
  keyOpText: "#93c5fd",
  keyFnBg: "#475569",
  keyFnText: "#e2e8f0",
  keyEqualsBg: "#2563eb",
  keyEqualsText: "#ffffff",
  calcDisplayBg: "#0f172a",
  switchTrackOff: "#475569",
  switchTrackOn: "#2563eb",
  switchThumb: "#f8fafc",
};
